import os
os.system("sudo apt-get update")
os.system("sudo apt-get upgrade")
os.system("sudo apt-get install dnsmasq")
dhcpcd = open("/etc/dhcpcd.conf", "a")
dhcpcd.write("\ninterface eth0")
dhcpcd.write("\nstatic ip_address=192.168.220.1/24")
dhcpcd.write("\nstatic routers=192.168.220.0")
dhcpcd.close()
os.system("sudo service dhcpcd restart")
os.system("sudo mv /etc/dnsmasq.conf /etc/dnsmasq.conf.orig")
dnsmasq = open("/etc/dnsmasq.conf", "w")
dnsmasq.write("interface=eth0\nlisten-address=192.168.1.1\nbind-interfaces\nserver=8.8.8.8\ndomain-needed\nbogus-priv\ndhcp-range=192.168.1.50,192.168.1.150,12h")
dnsmasq.close()
sysctl = open("/etc/sysctl.conf", "a")
sysctl.write("\nnet.ipv4.ip_forward=1")
sysctl.close()
os.system('sudo sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"')
print("Ready for step 2!")
