import os
dhcpcd = open("/etc/dhcpcd.conf","a")
dhcpcd.write("denyinterfaces eth0")
dhcpcd.close()
interfaces = open("sudo nano /etc/network/interfaces", "a")
interfaces.write("\nauto eth0")
interfaces.write("\nallow-hotplug eth0")
interfaces.write("\niface eth0 inet static")
interfaces.write("\n    address 192.168.1.1")
interfaces.write("\n    netmask 255.255.255.0")
interfaces.write("\n    network 192.168.1.0")
interfaces.write("\n    broadcast 192.168.1.255")
interfaces.close()
os.system("sudo apt-get install dnsmasq")
os.system("sudo mv /etc/dnsmasq.conf /etc/dnsmasq.conf.orig")
dnsmasq = open("/etc/dnsmasq.conf","a")
dnsmasq.write("\ninterface=eth0")
dnsmasq.write("\nlisten-address=192.168.1.1")
dnsmasq.write("\ndhcp-range=192.168.1.50,192.168.1.100,12h")
dnsmasq.write("\nserver=8.8.8.8")
dnsmasq.write("\nbind-interfaces")
dnsmasq.write("\ndomain-needed")
dnsmasq.write("\nbogus-priv")
dnsmasq.close()
interface = open("/etc/network/interfaces", "a")
interface.write("\nauto wlan0")
interface.write("\nallow-hotplug wlan0")
interface.write("\niface wlan0 inet manual")
interface.write("\nwpa-conf /etc/wpa_supplicant/wpa_supplicant.conf")
interface.close()
print("Restart Your PI.")
